# Generated by Django 4.1.6 on 2023-02-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hi',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('contactno', models.BigIntegerField()),
            ],
            options={
                'db_table': 'hello',
            },
        ),
    ]
